#!/bin/sh
# Re-generates src/engine/doom1.wad.b64.ts from engine/doom1.wad.
set -e
cd "$(dirname "$0")"
node -e '
const fs = require("fs"); const b = fs.readFileSync("doom1.wad").toString("base64");
fs.writeFileSync("../src/engine/doom1.wad.b64.ts", "// Shareware DOOM IWAD (doom1.wad, " + fs.statSync("doom1.wad").size.toLocaleString("en-US") + " bytes) as base64. Generated by engine/pack-wad.sh; do not edit.\n// The scene runtime has no binary fetch, so the WAD ships inside the bundle and is decoded at startup.\nexport const DOOM1_WAD_B64 =\n  \x27" + b + "\x27\n");
console.log("wrote src/engine/doom1.wad.b64.ts", b.length, "chars");'
